-- ============================================================================
-- Project      : Restaurant Management System
-- File         : create_tables.sql
-- Author       : Harshil Narola
-- DBMS         : PostgreSQL
-- Description  : Creates the Restaurant Management System database and all
--                database tables.
--
-- NOTE:
-- 1. Execute the CREATE DATABASE statement first.
-- 2. In pgAdmin, open the restaurant_management_system database.
-- 3. Execute the remaining CREATE TABLE statements.
-- ============================================================================


-- ============================================================================
-- MASTER TABLES
-- ============================================================================

-- ============================================================================
-- TABLE: Customer
-- Purpose: Stores customer information.
-- ============================================================================

CREATE TABLE IF NOT EXISTS Customer
(
    customer_id        INT GENERATED BY DEFAULT AS IDENTITY,
    name               VARCHAR(100) NOT NULL,
    mobile_number      VARCHAR(15)  NOT NULL,
    created_at         TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_customer
        PRIMARY KEY (customer_id),

    CONSTRAINT uq_customer_mobile_number
        UNIQUE (mobile_number),

    CONSTRAINT chk_customer_mobile_number
        CHECK (mobile_number ~ '^[0-9]{10}$')
);



-- ============================================================================
-- TABLE: Employee
-- Purpose: Stores employee information.
-- ============================================================================

CREATE TABLE IF NOT EXISTS Employee
(
    employee_id        INT GENERATED BY DEFAULT AS IDENTITY,
    name               VARCHAR(100) NOT NULL,
    phone_number       VARCHAR(15)  NOT NULL,
    role               VARCHAR(50)  NOT NULL,
    salary             DECIMAL(10,2) NOT NULL,
    hire_date          DATE         NOT NULL,
    status             VARCHAR(20)  NOT NULL DEFAULT 'Active',
    manager_id         INT,

    CONSTRAINT pk_employee
        PRIMARY KEY (employee_id),

    CONSTRAINT uq_employee_phone_number
        UNIQUE (phone_number),

    CONSTRAINT chk_employee_phone_number
        CHECK (phone_number ~ '^[0-9]{10}$'),

    CONSTRAINT chk_employee_salary
        CHECK (salary >= 0),

    CONSTRAINT chk_employee_role
        CHECK (role IN ('Manager','Cashier','Chef','Waiter')),

    CONSTRAINT chk_employee_status
        CHECK (status IN ('Active','Inactive')),

    CONSTRAINT fk_employee_manager
        FOREIGN KEY (manager_id)
        REFERENCES Employee(employee_id)
        ON DELETE SET NULL
        ON UPDATE CASCADE
);



-- ============================================================================
-- TABLE: Restaurant_Table
-- Purpose: Stores information about restaurant tables.
-- ============================================================================

CREATE TABLE IF NOT EXISTS Restaurant_Table
(
    table_number       INT,
    capacity           INT NOT NULL,
    status             VARCHAR(20) NOT NULL DEFAULT 'Available',

    CONSTRAINT pk_restaurant_table
        PRIMARY KEY (table_number),

    CONSTRAINT chk_table_capacity
        CHECK (capacity > 0),

    CONSTRAINT chk_table_status
        CHECK (status IN ('Available','Occupied','Reserved'))
);



-- ============================================================================
-- TABLE: Category
-- Purpose: Stores dish categories.
-- ============================================================================

CREATE TABLE IF NOT EXISTS Category
(
    category_name      VARCHAR(50),

    CONSTRAINT pk_category
        PRIMARY KEY (category_name),

    CONSTRAINT chk_category_name
        CHECK (LENGTH(TRIM(category_name)) > 0)
);



-- ============================================================================
-- TABLE: Dish
-- Purpose: Stores all dishes available in the restaurant.
-- ============================================================================

CREATE TABLE IF NOT EXISTS Dish
(
    dish_id            INT GENERATED BY DEFAULT AS IDENTITY,
    dish_name          VARCHAR(100) NOT NULL,
    price              DECIMAL(10,2) NOT NULL,
    status             VARCHAR(20) NOT NULL DEFAULT 'Available',
    category_name      VARCHAR(50) NOT NULL,

    CONSTRAINT pk_dish
        PRIMARY KEY (dish_id),

    CONSTRAINT uq_dish_name
        UNIQUE (dish_name),

    CONSTRAINT chk_dish_name
        CHECK (LENGTH(TRIM(dish_name)) > 0),

    CONSTRAINT chk_dish_price
        CHECK (price >= 0),

    CONSTRAINT chk_dish_status
        CHECK (status IN ('Available','Unavailable')),

    CONSTRAINT fk_dish_category
        FOREIGN KEY (category_name)
        REFERENCES Category(category_name)
        ON DELETE RESTRICT
        ON UPDATE CASCADE
);



-- ============================================================================
-- TABLE: Raw_Material
-- Purpose: Stores inventory of raw materials.
-- ============================================================================

CREATE TABLE IF NOT EXISTS Raw_Material
(
    material_id        INT GENERATED BY DEFAULT AS IDENTITY,
    material_name      VARCHAR(100) NOT NULL,
    current_stock      DECIMAL(10,2) NOT NULL DEFAULT 0,
    unit               VARCHAR(20) NOT NULL,
    minimum_stock      DECIMAL(10,2) NOT NULL,

    CONSTRAINT pk_raw_material
        PRIMARY KEY (material_id),

    CONSTRAINT uq_material_name
        UNIQUE (material_name),

    CONSTRAINT chk_material_name
        CHECK (LENGTH(TRIM(material_name)) > 0),

    CONSTRAINT chk_current_stock
        CHECK (current_stock >= 0),

    CONSTRAINT chk_minimum_stock
        CHECK (minimum_stock >= 0),

    CONSTRAINT chk_material_unit
        CHECK (unit IN ('kg','g','l','ml','pcs','pack'))
);



-- ============================================================================
-- TABLE: Supplier
-- Purpose: Stores supplier information.
-- ============================================================================

CREATE TABLE IF NOT EXISTS Supplier
(
    supplier_id        INT GENERATED BY DEFAULT AS IDENTITY,
    supplier_name      VARCHAR(100) NOT NULL,
    contact_person     VARCHAR(100) NOT NULL,
    phone_number       VARCHAR(15) NOT NULL,
    address            VARCHAR(200) NOT NULL,

    CONSTRAINT pk_supplier
        PRIMARY KEY (supplier_id),

    CONSTRAINT uq_supplier_phone_number
        UNIQUE (phone_number),

    CONSTRAINT chk_supplier_phone_number
        CHECK (phone_number ~ '^[0-9]{10}$'),

    CONSTRAINT chk_supplier_name
        CHECK (LENGTH(TRIM(supplier_name)) > 0),

    CONSTRAINT chk_contact_person
        CHECK (LENGTH(TRIM(contact_person)) > 0),

    CONSTRAINT chk_supplier_address
        CHECK (LENGTH(TRIM(address)) > 0)
);



-- ============================================================================
-- TRANSACTION TABLES
-- ============================================================================



-- ============================================================================
-- TABLE: Orders
-- Purpose: Stores all customer orders.
-- ============================================================================

CREATE TABLE IF NOT EXISTS Orders
(
    order_id             BIGINT GENERATED BY DEFAULT AS IDENTITY,
    order_date_time      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    status               VARCHAR(20) NOT NULL DEFAULT 'Pending',

    customer_id          INT NOT NULL,
    employee_id          INT NOT NULL,
    table_number         INT NOT NULL,

    CONSTRAINT pk_orders
        PRIMARY KEY (order_id),

    CONSTRAINT chk_order_status
        CHECK (
            status IN
            (
                'Pending',
                'Preparing',
                'Served',
                'Completed',
                'Cancelled'
            )
        ),

    CONSTRAINT fk_order_customer
        FOREIGN KEY (customer_id)
        REFERENCES Customer(customer_id)
        ON DELETE RESTRICT
        ON UPDATE CASCADE,

    CONSTRAINT fk_order_employee
        FOREIGN KEY (employee_id)
        REFERENCES Employee(employee_id)
        ON DELETE RESTRICT
        ON UPDATE CASCADE,

    CONSTRAINT fk_order_restaurant_table
        FOREIGN KEY (table_number)
        REFERENCES Restaurant_Table(table_number)
        ON DELETE RESTRICT
        ON UPDATE CASCADE
);



-- ============================================================================
-- TABLE: Bill
-- Purpose: Stores billing information for each order.
-- ============================================================================

CREATE TABLE IF NOT EXISTS Bill
(
    bill_id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    bill_date_time       TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    subtotal             DECIMAL(10,2) NOT NULL,
    tax                  DECIMAL(10,2) NOT NULL,
    discount             DECIMAL(10,2) NOT NULL DEFAULT 0,
    total_amount         DECIMAL(10,2) NOT NULL,

    payment_mode         VARCHAR(20) NOT NULL,
    payment_status       VARCHAR(20) NOT NULL DEFAULT 'Pending',

    order_id             BIGINT NOT NULL,

    CONSTRAINT pk_bill
        PRIMARY KEY (bill_id),

    CONSTRAINT uq_bill_order
        UNIQUE (order_id),

    CONSTRAINT chk_bill_subtotal
        CHECK (subtotal >= 0),

    CONSTRAINT chk_bill_tax
        CHECK (tax >= 0),

    CONSTRAINT chk_bill_discount
        CHECK
        (
            discount >= 0
            AND discount <= subtotal
        ),

    CONSTRAINT chk_bill_total_amount
        CHECK (total_amount >= 0),

    CONSTRAINT chk_bill_payment_mode
        CHECK
        (
            payment_mode IN
            (
                'Cash',
                'UPI',
                'Card'
            )
        ),

    CONSTRAINT chk_bill_payment_status
        CHECK
        (
            payment_status IN
            (
                'Pending',
                'Paid'
            )
        ),

    CONSTRAINT fk_bill_order
        FOREIGN KEY (order_id)
        REFERENCES Orders(order_id)
        ON DELETE RESTRICT
        ON UPDATE CASCADE
);



-- ============================================================================
-- TABLE: Purchase
-- Purpose: Stores supplier purchase transactions.
-- ============================================================================

CREATE TABLE IF NOT EXISTS Purchase
(
    purchase_id             BIGINT GENERATED BY DEFAULT AS IDENTITY,
    purchase_date_time      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    payment_date_time       TIMESTAMP,

    invoice_number          VARCHAR(50) NOT NULL,
    total_amount            DECIMAL(10,2) NOT NULL,
    status                  VARCHAR(20) NOT NULL DEFAULT 'Ordered',

    supplier_id             INT NOT NULL,

    CONSTRAINT pk_purchase
        PRIMARY KEY (purchase_id),

    CONSTRAINT uq_purchase_invoice
        UNIQUE (invoice_number),

    CONSTRAINT chk_purchase_invoice
        CHECK
        (
            LENGTH(TRIM(invoice_number)) > 0
        ),

    CONSTRAINT chk_purchase_total_amount
        CHECK
        (
            total_amount >= 0
        ),

    CONSTRAINT chk_purchase_status
        CHECK
        (
            status IN
            (
                'Ordered',
                'Delivered',
                'Cancelled'
            )
        ),

    CONSTRAINT fk_purchase_supplier
        FOREIGN KEY (supplier_id)
        REFERENCES Supplier(supplier_id)
        ON DELETE RESTRICT
        ON UPDATE CASCADE
);



-- ============================================================================
-- WEAK ENTITY
-- ============================================================================



-- ============================================================================
-- TABLE: Daily_Dish_Preparation
-- Purpose:
-- Stores the daily preparation details for each dish.
-- One record represents the quantity of a dish prepared on a particular day.
-- ============================================================================

CREATE TABLE IF NOT EXISTS Daily_Dish_Preparation
(
    dish_id                 INT,
    preparation_date        DATE NOT NULL DEFAULT CURRENT_DATE,

    prepared_quantity       INT NOT NULL,
    remaining_quantity      INT NOT NULL,

    CONSTRAINT pk_daily_dish_preparation
        PRIMARY KEY (dish_id, preparation_date),

    CONSTRAINT chk_prepared_quantity
        CHECK (prepared_quantity > 0),

    CONSTRAINT chk_remaining_quantity
        CHECK
        (
            remaining_quantity >= 0
            AND remaining_quantity <= prepared_quantity
        ),

    CONSTRAINT fk_daily_preparation_dish
        FOREIGN KEY (dish_id)
        REFERENCES Dish(dish_id)
        ON DELETE RESTRICT
        ON UPDATE CASCADE
);



-- ============================================================================
-- JUNCTION TABLES
-- ============================================================================



-- ============================================================================
-- TABLE: Dish_Recipe
-- Purpose:
-- Stores the recipe of each dish by specifying the quantity of each
-- raw material required to prepare one serving of the dish.
-- ============================================================================

CREATE TABLE IF NOT EXISTS Dish_Recipe
(
    dish_id                 INT,
    material_id             INT,
    quantity_required       DECIMAL(10,2) NOT NULL,

    CONSTRAINT pk_dish_recipe
        PRIMARY KEY (dish_id, material_id),

    CONSTRAINT chk_quantity_required
        CHECK (quantity_required > 0),

    CONSTRAINT fk_recipe_dish
        FOREIGN KEY (dish_id)
        REFERENCES Dish(dish_id)
        ON DELETE CASCADE
        ON UPDATE CASCADE,

    CONSTRAINT fk_recipe_material
        FOREIGN KEY (material_id)
        REFERENCES Raw_Material(material_id)
        ON DELETE RESTRICT
        ON UPDATE CASCADE
);



-- ============================================================================
-- TABLE: Supplier_Raw_Material
-- Purpose:
-- Represents which suppliers supply which raw materials.
-- Implements the many-to-many relationship between Supplier and Raw_Material.
-- ============================================================================

CREATE TABLE IF NOT EXISTS Supplier_Raw_Material
(
    supplier_id             INT,
    material_id             INT,

    CONSTRAINT pk_supplier_raw_material
        PRIMARY KEY (supplier_id, material_id),

    CONSTRAINT fk_supplier_material_supplier
        FOREIGN KEY (supplier_id)
        REFERENCES Supplier(supplier_id)
        ON DELETE RESTRICT
        ON UPDATE CASCADE,

    CONSTRAINT fk_supplier_material_raw_material
        FOREIGN KEY (material_id)
        REFERENCES Raw_Material(material_id)
        ON DELETE RESTRICT
        ON UPDATE CASCADE
);



-- ============================================================================
-- TABLE: Order_Item
-- Purpose:
-- Stores all dishes included in an order along with the ordered quantity.
-- Implements the many-to-many relationship between Orders and Dish.
-- ============================================================================

CREATE TABLE IF NOT EXISTS Order_Item
(
    order_id                BIGINT,
    dish_id                 INT,
    quantity                INT NOT NULL,

    CONSTRAINT pk_order_item
        PRIMARY KEY (order_id, dish_id),

    CONSTRAINT chk_order_item_quantity
        CHECK (quantity > 0),

    CONSTRAINT fk_order_item_order
        FOREIGN KEY (order_id)
        REFERENCES Orders(order_id)
        ON DELETE CASCADE
        ON UPDATE CASCADE,

    CONSTRAINT fk_order_item_dish
        FOREIGN KEY (dish_id)
        REFERENCES Dish(dish_id)
        ON DELETE RESTRICT
        ON UPDATE CASCADE
);



-- ============================================================================
-- TABLE: Purchase_Item
-- Purpose:
-- Stores the raw materials included in a purchase along with their
-- purchased quantity and unit price.
-- Implements the many-to-many relationship between Purchase and
-- Raw_Material.
-- ============================================================================

CREATE TABLE IF NOT EXISTS Purchase_Item
(
    purchase_id             BIGINT,
    material_id             INT,
    quantity                DECIMAL(10,2) NOT NULL,
    unit_price              DECIMAL(10,2) NOT NULL,

    CONSTRAINT pk_purchase_item
        PRIMARY KEY (purchase_id, material_id),

    CONSTRAINT chk_purchase_item_quantity
        CHECK (quantity > 0),

    CONSTRAINT chk_purchase_item_unit_price
        CHECK (unit_price >= 0),

    CONSTRAINT fk_purchase_item_purchase
        FOREIGN KEY (purchase_id)
        REFERENCES Purchase(purchase_id)
        ON DELETE CASCADE
        ON UPDATE CASCADE,

    CONSTRAINT fk_purchase_item_material
        FOREIGN KEY (material_id)
        REFERENCES Raw_Material(material_id)
        ON DELETE RESTRICT
        ON UPDATE CASCADE
);
-- ============================================================================